export const COMMON_BRANDS: string[] = [
  // Luxury
  "Alexander McQueen",
  "Alexander Wang",
  "Balenciaga",
  "Balmain",
  "Bottega Veneta",
  "Brunello Cucinelli",
  "Burberry",
  "Céline",
  "Chanel",
  "Chloé",
  "Christian Louboutin",
  "Dior",
  "Dolce & Gabbana",
  "Emporio Armani",
  "Fendi",
  "Giorgio Armani",
  "Givenchy",
  "Gucci",
  "Hermès",
  "Hugo Boss",
  "Jimmy Choo",
  "Lanvin",
  "Loewe",
  "Louis Vuitton",
  "Manolo Blahnik",
  "Miu Miu",
  "Moncler",
  "Moschino",
  "Mulberry",
  "Off-White",
  "Paul Smith",
  "Prada",
  "Saint Laurent",
  "Stella McCartney",
  "Stone Island",
  "Stuart Weitzman",
  "Ted Baker",
  "Tom Ford",
  "Valentino",
  "Versace",
  "Vivienne Westwood",
  // Streetwear / hype
  "A Bathing Ape",
  "Carhartt WIP",
  "Essentials",
  "Fear of God",
  "Golden Goose",
  "Palace",
  "Stüssy",
  "Supreme",
  // Contemporary / mid-market
  "A.P.C.",
  "Abercrombie & Fitch",
  "Acne Studios",
  "Adrianna Papell",
  "AG Jeans",
  "Aritzia",
  "Ann Taylor",
  "Banana Republic",
  "BCBGMAXAZRIA",
  "Brooks Brothers",
  "Calvin Klein",
  "Citizens of Humanity",
  "Club Monaco",
  "COS",
  "Diane von Furstenberg",
  "Diesel",
  "DL1961",
  "DKNY",
  "Eileen Fisher",
  "Everlane",
  "Express",
  "Frame",
  "Free People",
  "G-Star Raw",
  "Good American",
  "Hudson Jeans",
  "Isabel Marant",
  "J.Crew",
  "J. Jill",
  "Joe's Jeans",
  "Kate Spade",
  "Lafayette 148",
  "LOFT",
  "Madewell",
  "Maje",
  "Marc Jacobs",
  "Michael Kors",
  "Nautica",
  "Nicole Miller",
  "Nudie Jeans",
  "Paige",
  "Rag & Bone",
  "Ralph Lauren",
  "Reformation",
  "Sandro",
  "Talbots",
  "Theory",
  "Tommy Hilfiger",
  "Tory Burch",
  "Totême",
  "Vera Wang",
  "Vince",
  "White House Black Market",
  // American casual / mall
  "Aeropostale",
  "American Eagle",
  "Hollister",
  "Lane Bryant",
  "New York & Company",
  "PacSun",
  "Torrid",
  // High-street / fast fashion
  "& Other Stories",
  "ASOS",
  "Forever 21",
  "Gap",
  "H&M",
  "Mango",
  "Old Navy",
  "Primark",
  "Shein",
  "Topshop",
  "Uniqlo",
  "Zara",
  // Athletic / activewear
  "Adidas",
  "Alo Yoga",
  "ASICS",
  "Athleta",
  "Brooks",
  "Champion",
  "Fila",
  "Gymshark",
  "Hoka",
  "Lululemon",
  "New Balance",
  "Nike",
  "On",
  "Outdoor Voices",
  "Puma",
  "Reebok",
  "Salomon",
  "Saucony",
  "Sweaty Betty",
  "Tracksmith",
  "Under Armour",
  "Vuori",
  // Denim
  "7 For All Mankind",
  "Lee",
  "Levi's",
  "Madewell",
  "True Religion",
  "Wrangler",
  // Outdoor / workwear
  "Arc'teryx",
  "Canada Goose",
  "Carhartt",
  "Columbia",
  "Cotopaxi",
  "Eddie Bauer",
  "Fjällräven",
  "Keen",
  "L.L. Bean",
  "Lands' End",
  "Merrell",
  "Patagonia",
  "REI Co-op",
  "Sorel",
  "The North Face",
  "Timberland",
  // Footwear
  "Ariat",
  "Birkenstock",
  "Blundstone",
  "Chacos",
  "Clarks",
  "Cole Haan",
  "Converse",
  "Dr. Martens",
  "Frye",
  "Hunter",
  "Red Wing",
  "Sam Edelman",
  "Steve Madden",
  "Teva",
  "Thursday Boot Company",
  "UGG",
  "Vans",
  "Wolverine",
  // Lifestyle / misc
  "Allbirds",
  "Anthropologie",
  "Bonobos",
  "Coach",
  "Urban Outfitters",
  "Victoria's Secret",
];
