export const CANONICAL_CLOTHING_CATEGORIES = [
  "top",
  "bottom",
  "dress",
  "outerwear",
  "shoes",
  "accessory",
  "intimates",
  "swimwear",
] as const;

export type CanonicalClothingCategory = (typeof CANONICAL_CLOTHING_CATEGORIES)[number];

export const CATEGORY_LABELS: Record<CanonicalClothingCategory, string> = {
  top: "Top",
  bottom: "Bottom",
  dress: "Dress",
  outerwear: "Outerwear",
  shoes: "Shoes",
  accessory: "Accessory",
  intimates: "Intimates",
  swimwear: "Swimwear",
};

const CATEGORY_ALIASES: Record<string, CanonicalClothingCategory> = {
  accessories: "accessory",
  accessory: "accessory",
  bag: "accessory",
  bags: "accessory",
  backpack: "accessory",
  belt: "accessory",
  bikini: "swimwear",
  blazer: "outerwear",
  blouse: "top",
  boot: "shoes",
  boots: "shoes",
  bottom: "bottom",
  bottoms: "bottom",
  bra: "intimates",
  bralette: "intimates",
  cami: "top",
  camisole: "top",
  cardigan: "top",
  coat: "outerwear",
  crossbody: "accessory",
  dress: "dress",
  flat: "shoes",
  flats: "shoes",
  handbag: "accessory",
  hat: "accessory",
  heel: "shoes",
  heels: "shoes",
  hoodie: "top",
  intimates: "intimates",
  intimate: "intimates",
  jacket: "outerwear",
  jeans: "bottom",
  lingerie: "intimates",
  outerwear: "outerwear",
  pants: "bottom",
  peacoat: "outerwear",
  purse: "accessory",
  pumps: "shoes",
  sandal: "shoes",
  sandals: "shoes",
  scarf: "accessory",
  shirt: "top",
  shoe: "shoes",
  shoes: "shoes",
  short: "bottom",
  shorts: "bottom",
  skirt: "bottom",
  slippers: "shoes",
  sneaker: "shoes",
  sneakers: "shoes",
  sweater: "top",
  sweatshirt: "top",
  swimwear: "swimwear",
  swim: "swimwear",
  "swim top": "swimwear",
  "swim trunks": "swimwear",
  swimsuit: "swimwear",
  "bathing suit": "swimwear",
  "one-piece": "swimwear",
  "two-piece": "swimwear",
  "shoulder bag": "accessory",
  "tank top": "top",
  tank: "top",
  tee: "top",
  top: "top",
  tote: "accessory",
  tshirt: "top",
  "t-shirt": "top",
  underwear: "intimates",
  vest: "top",
  wallet: "accessory",
};

export const CATEGORY_LIKE_TAGS = new Set([
  "accessories",
  "accessory",
  "bag",
  "bags",
  "bottom",
  "bottoms",
  "dress",
  "intimate",
  "intimates",
  "outerwear",
  "shoe",
  "shoes",
  "swim",
  "swimwear",
  "top",
]);

export function normalizeCategory(value: unknown): CanonicalClothingCategory | "" {
  if (typeof value !== "string") {
    return "";
  }

  const normalized = value.trim().toLowerCase().replace(/\s+/g, " ");
  return CATEGORY_ALIASES[normalized] ?? "";
}
